INSERT INTO `permissions` (`name`, `guard_name`, `created_at`, `updated_at`) VALUES
('plan_view_internet', 'web', NOW(), NOW()),
('plan_add_internet', 'web', NOW(), NOW()),
('plan_edit_internet', 'web', NOW(), NOW()),
('plan_delete_internet', 'web', NOW(), NOW()),
('plan_export_internet', 'web', NOW(), NOW()),

('plan_view_voz', 'web', NOW(), NOW()),
('plan_add_voz', 'web', NOW(), NOW()),
('plan_edit_voz', 'web', NOW(), NOW()),
('plan_delete_voz', 'web', NOW(), NOW()),
('plan_export_voz', 'web', NOW(), NOW()),

('plan_view_custom', 'web', NOW(), NOW()),
('plan_add_custom', 'web', NOW(), NOW()),
('plan_edit_custom', 'web', NOW(), NOW()),
('plan_delete_custom', 'web', NOW(), NOW()),
('plan_export_custom', 'web', NOW(), NOW()),

('plan_view_package', 'web', NOW(), NOW()),
('plan_add_package', 'web', NOW(), NOW()),
('plan_edit_package', 'web', NOW(), NOW()),
('plan_delete_package', 'web', NOW(), NOW()),
('plan_export_package', 'web', NOW(), NOW()),

('crm_view_crm', 'web', NOW(), NOW()),
('crm_add_crm', 'web', NOW(), NOW()),
('crm_edit_crm', 'web', NOW(), NOW()),
('crm_delete_crm', 'web', NOW(), NOW()),
('crm_export_crm', 'web', NOW(), NOW()),
('crm_information_view_tab_crm', 'web', NOW(), NOW()),
('crm_document_view_tab_crm', 'web', NOW(), NOW()),

('client_view_client', 'web', NOW(), NOW()),
('client_add_client', 'web', NOW(), NOW()),
('client_edit_client', 'web', NOW(), NOW()),
('client_delete_client', 'web', NOW(), NOW()),
('client_export_client', 'web', NOW(), NOW()),
('client_view_dashboard', 'web', NOW(), NOW()),
('client_information_view_tab_client', 'web', NOW(), NOW()),
('client_service_view_tab_client', 'web', NOW(), NOW()),
('client_payroll_view_tab_client', 'web', NOW(), NOW()),

('seller_view_seller', 'web', NOW(), NOW()),
('seller_add_seller', 'web', NOW(), NOW()),
('seller_view_panel', 'web', NOW(), NOW()),
('seller_view_dashboard', 'web', NOW(), NOW()),

('panel_view_prospects', 'web', NOW(), NOW()),
('panel_view_sales', 'web', NOW(), NOW()),
('panel_view_stadistics', 'web', NOW(), NOW()),
('panel_view_billing', 'web', NOW(), NOW()),

('billing_payment_view_clients', 'web', NOW(), NOW()),
('billing_view_detail_payments', 'web', NOW(), NOW()),
('billing_payment_sellers', 'web', NOW(), NOW()),
('billing_view_transactions', 'web', NOW(), NOW()),

('seller_add_payment', 'web', NOW(), NOW()),
('seller_edit_payment', 'web', NOW(), NOW()),
('seller_delete_payment', 'web', NOW(), NOW()),
('seller_download_payment', 'web', NOW(), NOW()),

('ticket_view_open', 'web', NOW(), NOW()),
('ticket_add_open', 'web', NOW(), NOW()),
('ticket_edit_open', 'web', NOW(), NOW()),
('ticket_delete_open', 'web', NOW(), NOW()),
('ticket_export_open', 'web', NOW(), NOW()),

('ticket_view_close', 'web', NOW(), NOW()),
('ticket_add_close', 'web', NOW(), NOW()),
('ticket_edit_close', 'web', NOW(), NOW()),
('ticket_delete_close', 'web', NOW(), NOW()),
('ticket_export_close', 'web', NOW(), NOW()),

('ticket_view_recycling', 'web', NOW(), NOW()),
('ticket_add_recycling', 'web', NOW(), NOW()),
('ticket_edit_recycling', 'web', NOW(), NOW()),
('ticket_delete_recycling', 'web', NOW(), NOW()),
('ticket_export_recycling', 'web', NOW(), NOW()),
('ticket_view_dashboard', 'web', NOW(), NOW()),

('finance_view_transactions', 'web', NOW(), NOW()),
('finance_edit_transactions', 'web', NOW(), NOW()),
('finance_delete_transactions', 'web', NOW(), NOW()),
('finance_export_transactions', 'web', NOW(), NOW()),

('finance_view_billing', 'web', NOW(), NOW()),
('finance_edit_billing', 'web', NOW(), NOW()),
('finance_delete_billing', 'web', NOW(), NOW()),
('finance_export_billing', 'web', NOW(), NOW()),

('finance_view_payments', 'web', NOW(), NOW()),
('finance_edit_payments', 'web', NOW(), NOW()),
('finance_delete_payments', 'web', NOW(), NOW()),
('finance_export_payments', 'web', NOW(), NOW()),

('maps_view_maps', 'web', NOW(), NOW()),

('router_view_router', 'web', NOW(), NOW()),
('router_add_router', 'web', NOW(), NOW()),
('router_edit_router', 'web', NOW(), NOW()),
('router_delete_router', 'web', NOW(), NOW()),
('router_export_router', 'web', NOW(), NOW()),

('ipv4_view_ipv4', 'web', NOW(), NOW()),
('ipv4_add_ipv4', 'web', NOW(), NOW()),
('ipv4_edit_ipv4', 'web', NOW(), NOW()),
('ipv4_delete_ipv4', 'web', NOW(), NOW()),
('ipv4_export_ipv4', 'web', NOW(), NOW()),

('admin_view_module', 'web', NOW(), NOW()),
('admin_view_meganet', 'web', NOW(), NOW()),
('admin_view_registers', 'web', NOW(), NOW()),
('admin_view_information', 'web', NOW(), NOW()),
('admin_view_reports', 'web', NOW(), NOW()),

('config_view_module', 'web', NOW(), NOW()),
('config_view_system', 'web', NOW(), NOW()),
('config_view_main', 'web', NOW(), NOW()),
('config_view_finance', 'web', NOW(), NOW()),
('config_view_network_management', 'web', NOW(), NOW()),
('config_view_helpdesk', 'web', NOW(), NOW()),
('config_view_scheduling', 'web', NOW(), NOW()),
('config_view_potencial_customer', 'web', NOW(), NOW()),
('config_view_inventory', 'web', NOW(), NOW()),
('config_view_integrations', 'web', NOW(), NOW()),
('config_view_voice', 'web', NOW(), NOW()),
('config_view_tools', 'web', NOW(), NOW()),
('config_view_sales', 'web', NOW(), NOW()),
('config_view_google_maps', 'web', NOW(), NOW()),

('user_view_user', 'web', NOW(), NOW()),
('user_add_user', 'web', NOW(), NOW()),
('user_edit_user', 'web', NOW(), NOW()),
('user_delete_user', 'web', NOW(), NOW()),

('role_view_role', 'web', NOW(), NOW()),
('role_add_role', 'web', NOW(), NOW()),
('role_edit_role', 'web', NOW(), NOW()),
('role_delete_role', 'web', NOW(), NOW()),
('role_permission_role', 'web', NOW(), NOW()),

('partners_view_partners', 'web', NOW(), NOW()),
('partners_add_partners', 'web', NOW(), NOW()),
('partners_edit_partners', 'web', NOW(), NOW()),
('partners_delete_partners', 'web', NOW(), NOW()),
('partners_export_partners', 'web', NOW(), NOW()),

('location_view_location', 'web', NOW(), NOW()),
('location_add_location', 'web', NOW(), NOW()),
('location_edit_location', 'web', NOW(), NOW()),
('location_delete_location', 'web', NOW(), NOW()),
('location_export_location', 'web', NOW(), NOW()),

('apikey_view_apikey', 'web', NOW(), NOW()),

('state_view_state', 'web', NOW(), NOW()),
('state_add_state', 'web', NOW(), NOW()),
('state_edit_state', 'web', NOW(), NOW()),
('state_delete_state', 'web', NOW(), NOW()),
('state_export_state', 'web', NOW(), NOW()),

('municipality_view_municipality', 'web', NOW(), NOW()),
('municipality_add_municipality', 'web', NOW(), NOW()),
('municipality_edit_municipality', 'web', NOW(), NOW()),
('municipality_delete_municipality', 'web', NOW(), NOW()),
('municipality_export_municipality', 'web', NOW(), NOW()),

('colony_view_colony', 'web', NOW(), NOW()),
('colony_add_colony', 'web', NOW(), NOW()),
('colony_edit_colony', 'web', NOW(), NOW()),
('colony_delete_colony', 'web', NOW(), NOW()),
('colony_export_colony', 'web', NOW(), NOW()),

('method_payment_view_method_payment', 'web', NOW(), NOW()),
('method_payment_add_method_payment', 'web', NOW(), NOW()),
('method_payment_edit_method_payment', 'web', NOW(), NOW()),
('method_payment_delete_method_payment', 'web', NOW(), NOW()),
('method_payment_export_method_payment', 'web', NOW(), NOW()),

('ift_view_ift', 'web', NOW(), NOW()),
('ift_add_ift', 'web', NOW(), NOW()),
('ift_edit_ift', 'web', NOW(), NOW()),
('ift_delete_ift', 'web', NOW(), NOW()),
('ift_export_ift', 'web', NOW(), NOW()),

('package_view_package', 'web', NOW(), NOW()),

('additional_fields_view_additional_fields', 'web', NOW(), NOW()),
('additional_fields_add_additional_fields', 'web', NOW(), NOW()),
('additional_fields_edit_additional_fields', 'web', NOW(), NOW()),
('additional_fields_delete_additional_fields', 'web', NOW(), NOW()),
('additional_fields_export_additional_fields', 'web', NOW(), NOW()),

('labels_view_labels', 'web', NOW(), NOW()),

('translation_view_translation', 'web', NOW(), NOW()),

('admin_view_files', 'web', NOW(), NOW()),

('templates_view_templates', 'web', NOW(), NOW()),

('company_view_information', 'web', NOW(), NOW()),

-- permisos agregados
('dashboard_system_status', 'web', NOW(), NOW()),
('dashboard_clientes', 'web', NOW(), NOW()),
('dashboard_payroll', 'web', NOW(), NOW()),
('crm_information', 'web', NOW(), NOW()),
('crm_information_geolocation_crm', 'web', NOW(), NOW()),
('crm_document', 'web', NOW(), NOW()),
('crm_document_view_crm', 'web', NOW(), NOW()),
('crm_document_add_crm', 'web', NOW(), NOW()),
('crm_document_edit_crm', 'web', NOW(), NOW()),
('crm_document_delete_crm', 'web', NOW(), NOW()),
('client_information_geolocation_client', 'web', NOW(), NOW()),
('client_service', 'web', NOW(), NOW()),
('client_service_internet', 'web', NOW(), NOW()),
('client_service_internet_view_client', 'web', NOW(), NOW()),
('client_service_internet_add_client', 'web', NOW(), NOW()),
('client_service_internet_edit_client', 'web', NOW(), NOW()),
('client_service_internet_delete_client', 'web', NOW(), NOW()),
('client_service_voz', 'web', NOW(), NOW()),
('client_service_voz_view_client', 'web', NOW(), NOW()),
('client_service_voz_add_client', 'web', NOW(), NOW()),
('client_service_voz_edit_client', 'web', NOW(), NOW()),
('client_service_voz_delete_client', 'web', NOW(), NOW()),
('client_service_bundle', 'web', NOW(), NOW()),
('client_service_bundle_view_client', 'web', NOW(), NOW()),
('client_service_bundle_add_client', 'web', NOW(), NOW()),
('client_service_bundle_edit_client', 'web', NOW(), NOW()),
('client_service_bundle_delete_client', 'web', NOW(), NOW()),
('client_payroll', 'web', NOW(), NOW()),
('client_payroll_payment', 'web', NOW(), NOW()),
('client_payroll_payment_view_client', 'web', NOW(), NOW()),
('client_payroll_payment_add_client', 'web', NOW(), NOW()),
('client_payroll_payment_edit_client', 'web', NOW(), NOW()),
('client_payroll_payment_delete_client', 'web', NOW(), NOW());
