<?php

namespace App\Modules\Addons\Talento\Controllers;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Modules\Addons\Talento\Models\TalentoColaborador;
use App\Modules\Addons\Talento\Models\TalentoDevice;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class TalentoDeviceController extends Controller
{
    public function index()
    {
        $this->authorize('talento.devices.view');
        return view('addon-talento::talento.dispositivos');
    }

    /**
     * List devices for a collaborator.
     */
    public function forColaborador($colaboradorId)
    {
        $this->authorize('talento.devices.view');

        $colaborador = TalentoColaborador::findOrFail($colaboradorId);

        $devices = TalentoDevice::where('user_id', $colaborador->user_id)
            ->orderBy('created_at', 'desc')
            ->get();

        return response()->json($devices);
    }

    /**
     * Bind a device to a user.
     * Enforces one active device per user: revokes previous active device
     * (or flags approval_required if re-binding is needed).
     *
     * The device_key is generated by the app — never use IMEI or hardware ID.
     */
    public function bind(Request $request, $colaboradorId)
    {
        $this->authorize('talento.devices.manage');

        $colaborador = TalentoColaborador::findOrFail($colaboradorId);

        $data = $request->validate([
            'device_key' => 'required|string|max:128',
            'platform'   => 'nullable|in:android,ios,web',
            'label'      => 'nullable|string|max:100',
        ]);

        $userId     = $colaborador->user_id;
        $deviceKey  = $data['device_key'];
        $now        = now();

        // Check if same key already exists (re-connection)
        $existing = TalentoDevice::where('user_id', $userId)
            ->where('device_key', $deviceKey)
            ->first();

        if ($existing) {
            if ($existing->revoked_at) {
                // Previously revoked — requires approval to re-link
                $existing->update([
                    'approval_required' => true,
                    'approved'          => false,
                    'revoked_at'        => null,
                    'last_seen_at'      => $now,
                ]);
                return response()->json(['status' => 'pending_approval', 'device' => $existing], 202);
            }
            // Already active — just update last_seen
            $existing->update(['last_seen_at' => $now]);
            return response()->json(['status' => 'already_active', 'device' => $existing]);
        }

        // New device key: revoke any currently active device for this user
        TalentoDevice::where('user_id', $userId)
            ->whereNull('revoked_at')
            ->update(['revoked_at' => $now]);

        $device = TalentoDevice::create([
            'user_id'           => $userId,
            'device_key'        => $deviceKey,
            'platform'          => $data['platform'] ?? null,
            'label'             => $data['label'] ?? null,
            'approval_required' => false,
            'approved'          => true,
            'bound_at'          => $now,
            'last_seen_at'      => $now,
            'revoked_at'        => null,
        ]);

        return response()->json(['status' => 'bound', 'device' => $device], 201);
    }

    /**
     * Approve a re-binding request.
     */
    public function approve($colaboradorId, $deviceId)
    {
        $this->authorize('talento.devices.manage');

        $colaborador = TalentoColaborador::findOrFail($colaboradorId);
        $device = TalentoDevice::where('user_id', $colaborador->user_id)
            ->where('id', $deviceId)
            ->firstOrFail();

        // Revoke all other active devices
        TalentoDevice::where('user_id', $colaborador->user_id)
            ->where('id', '!=', $deviceId)
            ->whereNull('revoked_at')
            ->update(['revoked_at' => now()]);

        $device->update([
            'approval_required' => false,
            'approved'          => true,
            'bound_at'          => now(),
        ]);

        return response()->json(['status' => 'approved', 'device' => $device]);
    }

    /**
     * Revoke a device.
     */
    public function revoke($colaboradorId, $deviceId)
    {
        $this->authorize('talento.devices.manage');

        $colaborador = TalentoColaborador::findOrFail($colaboradorId);
        $device = TalentoDevice::where('user_id', $colaborador->user_id)
            ->where('id', $deviceId)
            ->firstOrFail();

        $device->update(['revoked_at' => now(), 'approved' => false]);

        return response()->json(['ok' => true]);
    }
}
